coreMvcFundamentals/Models/Customer.cs
namespace coreMvcFundamentals.Models
{
    public class Customer
    {
        //properties here
        public int Id { get; set; }

        public string? Name { get; set; }

        public double Amount { get; set; }
    }
}

coreMvcFundamentals/Models/ErrorViewModel.cs
namespace coreMvcFundamentals.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

coreMvcFundamentals/Models/InfoModel.cs
namespace coreMvcFundamentals.Models
{
    public class InfoModel
    {
        public int Id { get; set; }
        public string? Name { get; set; }

        public double Amount { get; set; }
    }
}

coreMvcFundamentals/Controllers/CustomerController.cs
using Microsoft.AspNetCore.Mvc;
using coreMvcFundamentals.Models;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace coreMvcFundamentals.Controllers
{
    public class CustomerController : Controller
    {
        //public static List<Models.Customer> customers = new List<Models.Customer>()
        public static List<Customer> customers = new List<Customer>()
        {
            new Customer(){ Id=101,Name="King", Amount=12000},
            new Customer(){ Id=102, Name="kochur",Amount=30000},
        };
        public IActionResult Index()
        {
            ViewBag.Message = "Customer Management System";
            ViewBag.CustomerCount = customers.Count();
            ViewBag.CustomerList = customers;
            return View();
        }
        public IActionResult Details()
        {
            return View();
        }
        //this is attribute method
        //this is default route for attribute routing [Route("~/")]
        //[Route ("/sample/message")]
        public IActionResult Message()
        {
            return View();
        }
    }
}

coreMvcFundamentals/Controllers/DemoController.cs
using coreMvcFundamentals.Models;
using Microsoft.AspNetCore.Mvc;

namespace coreMvcFundamentals.Controllers
{
    public class DemoController : Controller

    {
        public static List<Customer> customers = new List<Customer>()
        {
            new Customer(){Id=101,Name="King",Amount=12000},
            new Customer(){Id=102,Name="Kochur",Amount=20000},
        };
        //This is ViewBag Data
        public IActionResult Index()
        {
            ViewBag.Message = "Customer Management System";
            ViewBag.CustomerCount = customers.Count();
            ViewBag.CustomerList = customers;
            return View();
        }
        //This is ViewData
        public IActionResult Details()
        {
            ViewData["Message"] = "This is View Data Customer Management System";
            ViewData["CustomerCount"] = customers.Count();
            ViewData["CustomerList"] = customers;

            return View();
        }
        //This is TempData
        public IActionResult Method1()
        {
            TempData["Message"] = "This is TempData Customer managemnt System";
            TempData["CustomerCount"] = customers.Count();
            TempData["CustomerList"] = customers;
            return View();
        }
        public IActionResult Method2()
        {
            if (TempData["Message"] == null)
                return RedirectToAction("Index");
            TempData["Message"] = TempData["Message"].ToString();

            return View();
        }

        //this Controller is useing for session. //That is a Login Registration
        public IActionResult Login()
        {
            //Here I want to store Username to this login iteration
            //so I will SetString(),GetString() method because These will help to store the
            //values into the session. //username is Key and Bhawna is value

            HttpContext.Session.SetString("username", "Bhawna");
            
            //I wantedto travell another action method or another view.
            //the use RedirectToAction() instead of View()
            //Here "Success" is a method
            return RedirectToAction("Success");
        }
        //creating a Success method
        public IActionResult Success()
        {
            //what ever value i want to get in to the username that should be 
            //coming from the session
            ViewBag.Username = HttpContext.Session.GetString("username");
            
            
            return View();
        }
        //This is logout method
        public IActionResult Logout()
        {
            //whatever key you would to remove.Give the name.
            HttpContext.Session.Remove("Username");

         //post that redirect to action.Which page will show .Give the Action method
            return RedirectToAction("Index");
        }

        //how to pass Query String:
        //Request Url:http://localhost:5134/Demo/QueryTest
        //Request Url:http://localhost:5134/Demo/QueryTest?name=Bhawna%20Gunwani
        //Query String Method
        public IActionResult QueryTest()
        {
            string name = "King Kochur";
            if (!String.IsNullOrEmpty(HttpContext.Request.Query["name"]))
                name = HttpContext.Request.Query["name"];
            ViewBag.Name = name;
            return View();
        }


    }
}

coreMvcFundamentals/Controllers/HomeController.cs
using coreMvcFundamentals.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace coreMvcFundamentals.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

coreMvcFundamentals/Controllers/Practice1Controller.cs
using coreMvcFundamentals.Models;
using Microsoft.AspNetCore.Mvc;
using System.Security.Cryptography.X509Certificates;

namespace coreMvcFundamentals.Controllers
{
    public class Practice1Controller : Controller
    {
        public static List<InfoModel> users = new List<InfoModel>()
        {
            new InfoModel() { Id=200,Name="Bhabna Gunwani",Amount=2500 },
            new InfoModel() { Id=201,Name="Prity Lata", Amount=3500 },
            new InfoModel() { Id=203, Name="Angelical" ,Amount=1000 },
            new InfoModel() { Id=204, Name="Ada", Amount=5000 }

        };

        public IActionResult Info()
        {
            ViewBag.Message = "This is School Management System.";
            ViewBag.UserCount=users.Count();
            ViewBag.UserList = users;
            return View();

        }
        public IActionResult CallMethod()
        {
            if (ViewBag.Message == null)
                return RedirectToAction("Index");
            ViewBag.Message = ViewBag.Message.ToString();

            return View();
        }

       
        public IActionResult Index()
        {
            return View();
        }
       
    }
}

coreMvcFundamentals/Views/Customer/Details.cshtml
@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

coreMvcFundamentals/Views/Customer/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>
<h3>@ViewBag.Message</h3>
<p>There are @ViewBag.CustomerCount customers added into the list</p>
<ul>
    @foreach(var item in ViewBag.CustomerList)
    {
       <li> Id number : @item.Id -Name: @item.Name -Amount:@item.Amount </li>
        
    }

</ul>
<!-- 1st param: "ViewingDetails", 2nd param: "MethodName", 3rd Param:"ControllerName"-->
@Html.ActionLink("Detils page for Asp.net here","Details","Customer") 
<br />
<a asp-controller="Customer" asp-action="Message">Message </a>
<br/>
<button type="button" asp-controller="Customer" asp-action="Message">Go Message Method</button>

coreMvcFundamentals/Views/Customer/Message.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Message</title>
</head>
<body>
    <h1>This is Message View</h1>
</body>
</html>

coreMvcFundamentals/Views/Demo/Details.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    <h1>This is message: @ViewData["Message"]</h1>
    <h2>There are customer @ViewData["CustomerCount"] to the list.</h2>
    <table>
        <thead>
            <tr>
                <th>Customer Id</th>
                <th>Customer Name</th>
                <th>Customer Amount</th>
            </tr>
            <tbody>
                @foreach (var item in ViewData["CustomerList"] as List <Customer>) 
                {
                <tr>
                    <td>@item.Id</td>
                    <td>@item.Name</td>
                    <td>@item.Amount</td>

                </tr>
                }
                
            </tbody>
        </thead>
    </table>
</body>
</html>

coreMvcFundamentals/Views/Demo/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <h2>@ViewBag.Message</h2>
    <p>There are @ViewBag.CustomerCount customers added to the list</p>
    <table>
        <thead>
            <tr>
                <th>Customer Id</th>
                <th>Customer Name</th>
                <th>Customer Amount</th>
            </tr>

        </thead>
        <tbody>
            @foreach(var item in ViewBag.CustomerList)
            {
                <tr>
                    <td>@item.Id</td>
                    <td>@item.Name</td>
                    <td>@item.Amount</td>
                </tr>
            }
        </tbody>
    </table>
</body>
</html>

coreMvcFundamentals/Views/Demo/Method1.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Method1</title>
</head>
<body>
    <h1>This is message: @TempData["Message"]</h1>
    <h2>There are customer @TempData["CustomerCount"] to the list.</h2>
    <table>
        <thead>
            <tr>
                <th>Customer Id</th>
                <th>Customer Name</th>
                <th>Customer Amount</th>
            </tr>
        <tbody>
                @foreach (var item in TempData["CustomerList"] as List<Customer>)
                {
                <tr>
                    <td>@item.Id</td>
                    <td>@item.Name</td>
                    <td>@item.Amount</td>

                </tr>
                }

        </tbody>
        </thead>
    </table>
    <br />
    <!--For method two-->
    @{
        TempData.Keep("Message");
    }
    <!-- For method  two-->
    <a asp-controller="Demo" asp-action="Method2">Go Method2</a>

</body>
</html>

coreMvcFundamentals/Views/Demo/Method2.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Method2</title>
</head>
<body>
    <h1>@TempData["Message"]</h1>
</body>
</html>

coreMvcFundamentals/Views/Demo/QueryTest.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>QueryTest</title>
</head>
<body>
    <h2>@ViewBag.Name</h2>
</body>
</html>

coreMvcFundamentals/Views/Demo/Success.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Success</title>
</head>
<body>
    <h2>Welcome dear, @ViewBag.Username in this MVC Course</h2>
    <a asp-controller="Demo" asp-action="Logout">Logout</a>
</body>
</html>

coreMvcFundamentals/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

coreMvcFundamentals/Views/Practice1/CallMethod.cshtml
@{
    ViewData["Title"] = "CallMethod";
}

<h1>CallMethod</h1>
@{
    ViewBag.Name("Message");
}
<a asp-controller="Practice1" asp-action="CallMethod">Go To CallMethod</a>

@*

<!--For method two-->
@{
    TempData.Keep("Message");
}
<!-- For method  two-->
<a asp-controller="Demo" asp-action="Method2">Go Method2</a>
*@
   

coreMvcFundamentals/Views/Practice1/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>
<a asp-controller="Practice1" asp-action="CallMethod">Go To CallMethod</a>

coreMvcFundamentals/Views/Practice1/Info.cshtml
@{
    ViewData["Title"] = "Info";
}

<h1>Info</h1>

<h1>@ViewBag.Message</h1>
@foreach (var item in ViewBag.UserList)

{

    <table class="table">
        <thead>
            <tr>
           

                <th>ID</th>
                <th>NAME</th>
                <th>AMOUNT</th>
            
            </tr>
    </thead>
       <tbody>
        
            <tr>
                <td>@item.Id</td>
                <td>@item.Name</td>
                <td>@item.Amount</td>
            </tr>

     
       </tbody>
             
                
        
    </table>

    @* 
 <li>Instructor Id:@item.Id</li>
    <li>Instructor Name: @item.Name</li>
    <li>Instructor Amount:@item.Amount</li>
    *@
    
}
<a asp-controller="Practice" asp-action="">Go CallMethod</a>

coreMvcFundamentals/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - coreMvcFundamentals</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/coreMvcFundamentals.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">coreMvcFundamentals</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - coreMvcFundamentals - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>